"use client";

import { useState } from "react";
import { Loader2, PackagePlus } from "lucide-react";
import { useRouter } from "next/navigation";
import { useCart } from "@/context/CartContext";

type Product = { _id: string; name: string; thumbnail?: string; price: number; stock: number; status: string; sizes: string[]; colors: string[] };
type Combo = { _id: string; name: string; products: Product[]; originalPrice: number; comboPrice: number; savings: number; discountPercent: number; offerText?: string };

export default function ComboOfferCard({ combo }: { combo: Combo }) {
  const router = useRouter(); const { refreshCart } = useCart();
  const [values, setValues] = useState<Record<string, { size: string; color: string }>>(() => Object.fromEntries(combo.products.map((product) => [product._id, { size: product.sizes?.[0] || "", color: product.colors?.[0] || "" }])));
  const [loading, setLoading] = useState(false); const [error, setError] = useState("");
  const valid = combo.products.every((product) => product.stock > 0 && product.status === "Active" && (!product.sizes?.length || values[product._id]?.size) && (!product.colors?.length || values[product._id]?.color));
  async function buyCombo() {
    if (!valid) { setError("Select all required size and colour options."); return; }
    try { setLoading(true); setError(""); const response = await fetch("/api/cart/add-combo", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ comboId: combo._id, quantity: 1, selections: combo.products.map((product) => ({ productId: product._id, ...values[product._id] })) }) }); if (response.status === 401) { router.push("/login"); return; } const data = await response.json(); if (!response.ok) throw new Error(data.message || "Unable to add combo."); await refreshCart(); router.push("/cart"); } catch (reason) { setError(reason instanceof Error ? reason.message : "Unable to add combo."); } finally { setLoading(false); }
  }
  return <section className="rounded-2xl border-2 border-black bg-gray-50 p-5"><div className="flex items-start justify-between gap-4"><div><p className="text-xs font-bold uppercase tracking-wider text-gray-500">Combo Offer</p><h2 className="mt-1 text-xl font-bold">{combo.name}</h2>{combo.offerText && <p className="mt-1 text-sm text-gray-600">{combo.offerText}</p>}</div><span className="rounded-full bg-black px-3 py-1 text-xs font-bold text-white">Save ₹{combo.savings}</span></div><div className="mt-5 space-y-4">{combo.products.map((product) => <div className="rounded-xl bg-white p-3" key={product._id}><div className="flex items-center gap-3">{product.thumbnail ? <img src={product.thumbnail} alt="" className="h-14 w-14 rounded-lg object-cover" /> : <div className="h-14 w-14 rounded-lg bg-gray-100" />}<div><p className="font-semibold">{product.name}</p><p className="text-sm text-gray-500">₹{product.price.toLocaleString("en-IN")}</p></div></div><div className="mt-3 grid gap-2 sm:grid-cols-2">{product.sizes?.length > 0 && <select value={values[product._id]?.size || ""} onChange={(e) => setValues((current) => ({ ...current, [product._id]: { ...current[product._id], size: e.target.value } }))} className="rounded-lg border px-3 py-2 text-sm"><option value="">Select size</option>{product.sizes.map((size) => <option key={size}>{size}</option>)}</select>}{product.colors?.length > 0 && <select value={values[product._id]?.color || ""} onChange={(e) => setValues((current) => ({ ...current, [product._id]: { ...current[product._id], color: e.target.value } }))} className="rounded-lg border px-3 py-2 text-sm"><option value="">Select colour</option>{product.colors.map((color) => <option key={color}>{color}</option>)}</select>}</div></div>)}</div><div className="mt-5 flex items-end justify-between"><div><p className="text-sm text-gray-400 line-through">₹{combo.originalPrice.toLocaleString("en-IN")}</p><p className="text-2xl font-bold">₹{combo.comboPrice.toLocaleString("en-IN")}</p><p className="text-xs font-semibold text-green-700">{combo.discountPercent}% off</p></div><button type="button" disabled={loading || !valid} onClick={buyCombo} className="inline-flex items-center gap-2 rounded-full bg-black px-5 py-3 font-semibold text-white disabled:opacity-50">{loading ? <Loader2 size={17} className="animate-spin" /> : <PackagePlus size={17} />}{loading ? "Adding…" : "Buy Combo"}</button></div>{error && <p className="mt-3 text-sm text-red-600">{error}</p>}</section>;
}
